### PR TITLE
Feature/backend error handling

### PR DESCRIPTION
**Pull request by hafiz1379**
#### Overview
This PR adds a robust error-handling system to improve reliability and user experience across the app.

#### Key Updates:
1. **ErrorHandler Utility Class** ⚙️:
   - Custom `ErrorHandler` class for managing errors with status codes and messages.

2. **API Error Handling Middleware** 🛠️:
   - Middleware to capture and process unhandled errors consistently.

3. **Integrated Error Handling** 🔗:
   - Combined `ErrorHandler` with middleware for seamless error management.

4. **Refactored `getProductDetails` Controller** 🛒:
   - Added error handling to ensure smooth product details retrieval.

Looking forward to your feedback! 😊

### CODE REVIEW

**Comment by M-Anwar-Hussaini** [comment]
Hi dear @hafiz1379 .
# PR Approval: Enhanced Error Handling 🚀

The following changes have been thoroughly reviewed and tested:

1. **ErrorHandler Utility Class ⚙️:**
    - The custom `ErrorHandler` class is working perfectly, efficiently managing errors with standardized status codes and messages.

2. **API Error Handling Middleware 🛠️:**
    - The middleware for capturing and processing unhandled errors is functioning flawlessly, ensuring consistent error handling across the application.

3. **Integrated Error Handling 🔗:**
    - The integration of `ErrorHandler` with the middleware is seamless and works perfectly, providing unified and effective error management.

4. **Refactored `getProductDetails` Controller 🛒:**
    - The `getProductDetails` controller has been refactored successfully, and the error handling added is operating perfectly, ensuring smooth and reliable product detail retrieval.

**Approved** ✅

**Review by M-Anwar-Hussaini — COMMENTED** [review]
Hi dear @hafiz1379 .
# PR Approval: Enhanced Error Handling 🚀

The following changes have been thoroughly reviewed and tested:

1. **ErrorHandler Utility Class ⚙️:**
    - The custom `ErrorHandler` class is working perfectly, efficiently managing errors with standardized status codes and messages.

2. **API Error Handling Middleware 🛠️:**
    - The middleware for capturing and processing unhandled errors is functioning flawlessly, ensuring consistent error handling across the application.

3. **Integrated Error Handling 🔗:**
    - The integration of `ErrorHandler` with the middleware is seamless and works perfectly, providing unified and effective error management.

4. **Refactored `getProductDetails` Controller 🛒:**
    - The `getProductDetails` controller has been refactored successfully, and the error handling added is operating perfectly, ensuring smooth and reliable product detail retrieval.

**Approved** ✅

**Comment by M-Anwar-Hussaini** [comment]
# Pull Request: Comprehensive Error Handling and Code Refactor 🚀

This PR addresses several critical improvements to the error handling and code structure of the application. The following tasks were completed to enhance reliability and maintainability:

## Key Updates:

- [x] **Refactor the code** 🔄: General refactoring was performed to improve code readability and maintainability.
  
- [x] **Handle the Unhandled Promise rejections** 🚫: Added logic to properly handle unhandled promise rejections across the application, preventing potential crashes.

- [x] **Handle the `uncaughtException` error in the `app.js` file** 🛑: Implemented a handler for `uncaughtException` to gracefully handle unexpected errors and ensure the app does not crash unexpectedly.

- [x] **Create a reusable `catchAsync` function** 🔧: Developed a `catchAsync` utility function that efficiently wraps asynchronous functions, ensuring proper error handling in async-await and promise-based code.

- [x] **Wrap all the product controllers inside the `catchAsync` function** 📦: Refactored all product-related controllers to use the new `catchAsync` function, enhancing error management consistency.

- [x] **Rename the `catchAsync` function to a descriptive name** ✏️: The function was renamed to provide better clarity on its purpose and usage within the codebase.

- [x] **Fix a small typo in the `ErrorHandler` file for the class name** 📝: Corrected a minor typo in the `ErrorHandler` class name to maintain code quality and consistency.

- [x] **Handle invalid Mongoose ID error** 🆔: Added validation and error handling for invalid Mongoose IDs, ensuring that requests with malformed IDs are properly managed.

- [x] **Handle validation errors** ✅: Implemented robust validation error handling to provide clear and informative error messages to users when input data does not meet the required criteria.

---

These changes ensure a more robust, error-resilient application and improve overall code quality. Looking forward to your review and feedback!

**Comment by hafiz1379** [comment]
### Approval: Comprehensive Error Handling and Code Refactor ✅

Excellent work on this pull request! You've addressed critical aspects of error handling and improved the overall structure and reliability of the application. The following highlights stand out:

- **Code Refactoring** 🔄: The refactor enhances code readability and maintainability, making the codebase easier to work with and extend in the future.
  
- **Promise Rejections Handling** 🚫: Handling unhandled promise rejections effectively prevents potential application crashes, which is a crucial improvement.
  
- **Uncaught Exception Management** 🛑: Adding a handler for uncaught exceptions ensures that unexpected errors are handled gracefully without crashing the app.
  
- **Reusable `catchAsync` Function** 🔧: The creation and renaming of the `catchAsync` function to something more descriptive is a thoughtful touch, ensuring clarity and consistency throughout the codebase.
  
- **Improved Error Handling** 🆔✅: The addition of error handling for invalid Mongoose IDs and validation errors strengthens the app’s resilience against user input issues.

This PR significantly raises the quality and robustness of the application. Approved! 🚀 Keep up the excellent work!

**Pull request merged**
